name: Scheduled Selenium Scraper

on:
  
  schedule:
    # Runs at 6:00 AM, 2:00 PM, and 10:00 PM UTC daily
    - cron: '*/5 * * * *' 
    # - cron: '30 8,14,22 * * *'
    # - cron: '12 8 * * *'
  workflow_dispatch: 
permissions:
  contents: write
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your script
        run: python3 main.py
        
      - name: List files to debug
        run: ls -l nse_data/
        
      - name: Commit and push scraped data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          # Make sure folder exists (optional)
          mkdir -p nse_data
      
          git add nse_data/nse_preopen_*.json
      
          git commit -m "Add scraped data file $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
      
          # Push using token authentication
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
