name: Scheduled Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    # Runs at 6:00 AM, 2:00 PM, and 10:00 PM UTC daily
    - cron: '0 6,14,22 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your script
        run: python main.py
