name: Scheduled Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    # Runs at 6:00 AM, 2:00 PM, and 10:00 PM UTC daily
    - cron: '0 6,14,22 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your script
        run: python3 main.py

      - name: Commit and push scraped data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Check if folder exists and has files before adding
          if [ -d "nse_data" ] && ls nse_data/nse_preopen_*.json 1> /dev/null 2>&1; then
            git add nse_data/nse_preopen_*.json
            git commit -m "Add scraped data file $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
            
            # Set remote URL with token for auth
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No new scraped files to commit"
          fi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

